import yt1 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ.png"
import yt2 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ-1.png"
import yt3 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ-2.png"
import yt4 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ-3.png"
import yt5 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ (2).png"
import yt6 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ-1 (2).png"
import yt7 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ-2 (2).png"
import yt8 from "../../assets/svgs/tribe/images/unsplash_1i-P178kxHQ-3 (2).png"
import user1a from "../../assets/svgs/tribe/users1/Ellipse 19.png"
import user1b from "../../assets/svgs/tribe/users1/Ellipse 20.png"
import user1c from "../../assets/svgs/tribe/users1/Ellipse 21.png"
import user1d from "../../assets/svgs/tribe/users1/Ellipse 22.png"
import user2a from "../../assets/svgs/tribe/users2/Ellipse 19.png"
import user2b from "../../assets/svgs/tribe/users2/Ellipse 20.png"
import user2c from "../../assets/svgs/tribe/users2/Ellipse 21.png"
import user2d from "../../assets/svgs/tribe/users2/Ellipse 22.png"
import user3a from "../../assets/svgs/tribe/users3/Ellipse 19.png"
import user3b from "../../assets/svgs/tribe/users3/Ellipse 20.png"
import user3c from "../../assets/svgs/tribe/users3/Ellipse 21.png"
import user3d from "../../assets/svgs/tribe/users3/Ellipse 22.png"
import tjdt from "../../assets/svgs/tribe/tribes-joined-discover-tribe.png"
import tjdtuser1 from "../../assets/svgs/tribe/tjdt/Ellipse 19.png"
import tjdtuser2 from "../../assets/svgs/tribe/tjdt/Ellipse 20.png"
import tjdtuser3 from "../../assets/svgs/tribe/tjdt/Ellipse 21.png"
import tjdtuser4 from "../../assets/svgs/tribe/tjdt/Ellipse 22.png"

const yourTribeNail = [
    {
        id: 1,
        image: yt1,
        title: "Marketing",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
        ],
    },
    {
        id: 2,
        image: yt2,
        title: "Droppers",
        amount: "Free",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
        ],
    },
    {
        id: 3,
        image: yt3,
        title: "Designers Corner",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
        ],
    },
    {
        id: 4,
        image: yt4,
        title: "Developers",
        amount: "Free",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
        ],
    },
    {
        id: 5,
        image: yt5,
        title: "Lead",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
            user1a,
            user1b,
            user1c,
            user1d,
        ],
    },
    {
        id: 6,
        image: yt6,
        title: "Top Guys in Tech",
        amount: "Free",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
        ],
    },
    {
        id: 7,
        image: yt7,
        title: "Hit List",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
            user3a,
            user3b,
            user3c,
            user3d,
        ],
    },
    {
        id: 8,
        image: yt8,
        title: "Favourite Guess",
        amount: "Free",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
            user2a,
            user2b,
            user2c,
            user2d,
        ],
    },
]

const tribesJoinedNail = [
    {
        id: 1,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
    {
        id: 2,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
    {
        id: 3,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
    {
        id: 4,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "70 pending approval",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
]

const discoverTribesNail = [
    {
        id: 1,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "Join",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
    {
        id: 2,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "Join",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
    {
        id: 3,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "Join",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
    {
        id: 4,
        image: tjdt,
        title: "Marketing",
        amount: "$1,000",
        status: "Pending",
        membersNumber: "+30 members",
        membersImage: [
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
            tjdtuser1,
            tjdtuser2,
            tjdtuser3,
            tjdtuser4,
        ],
    },
]

export {yourTribeNail, tribesJoinedNail, discoverTribesNail}